// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkEmailUsername = `-- name: CheckEmailUsername :one
SELECT
    EXISTS(SELECT 1 FROM users u WHERE u.email = $1) AS email_exists,
    EXISTS(SELECT 1 FROM users u WHERE u.username = $2) AS username_exists
`

type CheckEmailUsernameParams struct {
	Email    string
	Username string
}

type CheckEmailUsernameRow struct {
	EmailExists    bool
	UsernameExists bool
}

func (q *Queries) CheckEmailUsername(ctx context.Context, arg CheckEmailUsernameParams) (CheckEmailUsernameRow, error) {
	row := q.db.QueryRow(ctx, checkEmailUsername, arg.Email, arg.Username)
	var i CheckEmailUsernameRow
	err := row.Scan(&i.EmailExists, &i.UsernameExists)
	return i, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, username, email, password_hash
) VALUES (
    $1, $2, $3, $4
) RETURNING id, username, email, is_active
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
}

type CreateUserRow struct {
	ID       uuid.UUID
	Username string
	Email    string
	IsActive bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsActive,
	)
	return i, err
}

const findUserByCredential = `-- name: FindUserByCredential :one
SELECT id, username, email, password_hash, is_active
FROM users
WHERE email = $1 OR username = $1
LIMIT 1
`

type FindUserByCredentialRow struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	IsActive     bool
}

func (q *Queries) FindUserByCredential(ctx context.Context, credential string) (FindUserByCredentialRow, error) {
	row := q.db.QueryRow(ctx, findUserByCredential, credential)
	var i FindUserByCredentialRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, is_active
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	IsActive     bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, is_active
FROM users
WHERE username = $1
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	IsActive     bool
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}
