// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (id, post_id, author_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, author_id, content, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	ID       uuid.UUID
	PostID   uuid.UUID
	AuthorID uuid.UUID
	Content  string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.PostID,
		arg.AuthorID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentByIDForUpdate = `-- name: GetCommentByIDForUpdate :one
SELECT id, post_id, author_id, content, created_at, updated_at, deleted_at
FROM comments
WHERE id = $1 AND post_id = $2
FOR UPDATE
`

type GetCommentByIDForUpdateParams struct {
	ID     uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) GetCommentByIDForUpdate(ctx context.Context, arg GetCommentByIDForUpdateParams) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByIDForUpdate, arg.ID, arg.PostID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPostByIDForComment = `-- name: GetPostByIDForComment :one
SELECT id
FROM posts
WHERE id = $1
`

func (q *Queries) GetPostByIDForComment(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPostByIDForComment, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const listCommentsByPost = `-- name: ListCommentsByPost :many
SELECT id, post_id, author_id, content, created_at, updated_at, deleted_at
FROM comments
WHERE post_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListCommentsByPostParams struct {
	PostID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListCommentsByPost(ctx context.Context, arg ListCommentsByPostParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByPost, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :one
UPDATE comments
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND post_id = $2 AND deleted_at IS NULL
RETURNING id, post_id, author_id, content, created_at, updated_at, deleted_at
`

type SoftDeleteCommentParams struct {
	ID     uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, softDeleteComment, arg.ID, arg.PostID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $3, updated_at = now()
WHERE id = $1 AND post_id = $2 AND deleted_at IS NULL
RETURNING id, post_id, author_id, content, created_at, updated_at, deleted_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID
	PostID  uuid.UUID
	Content string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.PostID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
