// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Revoked   bool
	UserAgent pgtype.Text
	Ip        pgtype.Text
	DeviceID  pgtype.Text
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	DisplayName  pgtype.Text
	Bio          pgtype.Text
	AvatarUrl    pgtype.Text
	BannerUrl    pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
