// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_like.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const likePost = `-- name: LikePost :exec
INSERT INTO post_likes (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT (post_id, user_id) DO NOTHING
`

type LikePostParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) error {
	_, err := q.db.Exec(ctx, likePost, arg.PostID, arg.UserID)
	return err
}

const unlikePost = `-- name: UnlikePost :exec
DELETE FROM post_likes
WHERE post_id = $1 AND user_id = $2
`

type UnlikePostParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) error {
	_, err := q.db.Exec(ctx, unlikePost, arg.PostID, arg.UserID)
	return err
}
