// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const batchInsertPostImages = `-- name: BatchInsertPostImages :exec
INSERT INTO post_images (post_id, upload_id, position)
SELECT $1, unnest($2::uuid[]), unnest($3::smallint[])
`

type BatchInsertPostImagesParams struct {
	PostID  uuid.UUID
	Column2 []uuid.UUID
	Column3 []int16
}

func (q *Queries) BatchInsertPostImages(ctx context.Context, arg BatchInsertPostImagesParams) error {
	_, err := q.db.Exec(ctx, batchInsertPostImages, arg.PostID, arg.Column2, arg.Column3)
	return err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, author_id, title, content)
VALUES ($1, $2, $3, $4)
RETURNING id, author_id, title, content, created_at, updated_at
`

type CreatePostParams struct {
	ID       uuid.UUID
	AuthorID uuid.UUID
	Title    string
	Content  string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const deletePostImages = `-- name: DeletePostImages :exec
DELETE FROM post_images
WHERE post_id = $1 AND upload_id = ANY($2::uuid[])
`

type DeletePostImagesParams struct {
	PostID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) DeletePostImages(ctx context.Context, arg DeletePostImagesParams) error {
	_, err := q.db.Exec(ctx, deletePostImages, arg.PostID, arg.Column2)
	return err
}

const deletePostImagesByPostID = `-- name: DeletePostImagesByPostID :many
DELETE FROM post_images
WHERE post_id = $1
RETURNING upload_id
`

func (q *Queries) DeletePostImagesByPostID(ctx context.Context, postID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deletePostImagesByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var upload_id uuid.UUID
		if err := rows.Scan(&upload_id); err != nil {
			return nil, err
		}
		items = append(items, upload_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByIDForUpdate = `-- name: GetPostByIDForUpdate :one
SELECT id, author_id, title, content, created_at, updated_at
FROM posts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPostByIDForUpdate(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByIDForUpdate, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostImagesByPostIDs = `-- name: GetPostImagesByPostIDs :many
SELECT pi.post_id, pi.upload_id, pi.position, pi.created_at,
       u.object_key, u.content_type
FROM post_images pi
JOIN uploads u ON pi.upload_id = u.id
WHERE pi.post_id = ANY($1::uuid[])
ORDER BY pi.post_id, pi.position ASC
`

type GetPostImagesByPostIDsRow struct {
	PostID      uuid.UUID
	UploadID    uuid.UUID
	Position    int16
	CreatedAt   pgtype.Timestamptz
	ObjectKey   string
	ContentType pgtype.Text
}

func (q *Queries) GetPostImagesByPostIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetPostImagesByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, getPostImagesByPostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostImagesByPostIDsRow
	for rows.Next() {
		var i GetPostImagesByPostIDsRow
		if err := rows.Scan(
			&i.PostID,
			&i.UploadID,
			&i.Position,
			&i.CreatedAt,
			&i.ObjectKey,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostWithImagesByID = `-- name: GetPostWithImagesByID :many
SELECT p.id, p.author_id, p.title, p.content, p.created_at, p.updated_at,
       pi.upload_id, pi.position, pi.created_at AS image_created_at,
       u.object_key, u.content_type
FROM posts p
LEFT JOIN post_images pi ON p.id = pi.post_id
LEFT JOIN uploads u ON pi.upload_id = u.id
WHERE p.id = $1
ORDER BY pi.position ASC
`

type GetPostWithImagesByIDRow struct {
	ID             uuid.UUID
	AuthorID       uuid.UUID
	Title          string
	Content        string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	UploadID       pgtype.UUID
	Position       pgtype.Int2
	ImageCreatedAt pgtype.Timestamptz
	ObjectKey      pgtype.Text
	ContentType    pgtype.Text
}

func (q *Queries) GetPostWithImagesByID(ctx context.Context, id uuid.UUID) ([]GetPostWithImagesByIDRow, error) {
	rows, err := q.db.Query(ctx, getPostWithImagesByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostWithImagesByIDRow
	for rows.Next() {
		var i GetPostWithImagesByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UploadID,
			&i.Position,
			&i.ImageCreatedAt,
			&i.ObjectKey,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT id, author_id, title, content, created_at, updated_at
FROM posts
WHERE author_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByAuthorParams struct {
	AuthorID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthor, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPosts = `-- name: ListRecentPosts :many
SELECT id, author_id, title, content, created_at, updated_at
FROM posts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentPostsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRecentPosts(ctx context.Context, arg ListRecentPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listRecentPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = COALESCE($2, title),
    content = COALESCE($3, content),
    updated_at = now()
WHERE id = $1
RETURNING id, author_id, title, content, created_at, updated_at
`

type UpdatePostParams struct {
	ID      uuid.UUID
	Title   pgtype.Text
	Content pgtype.Text
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost, arg.ID, arg.Title, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePostImagePositions = `-- name: UpdatePostImagePositions :exec
UPDATE post_images AS pi
SET position = u.pos
FROM (SELECT unnest($2::uuid[]) AS upload_id, unnest($3::smallint[]) AS pos) AS u
WHERE pi.post_id = $1 AND pi.upload_id = u.upload_id
`

type UpdatePostImagePositionsParams struct {
	PostID  uuid.UUID
	Column2 []uuid.UUID
	Column3 []int16
}

func (q *Queries) UpdatePostImagePositions(ctx context.Context, arg UpdatePostImagePositionsParams) error {
	_, err := q.db.Exec(ctx, updatePostImagePositions, arg.PostID, arg.Column2, arg.Column3)
	return err
}
