// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, user_id, expires_at, created_at, revoked, user_agent, ip, device_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateSessionParams struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Revoked   bool
	UserAgent pgtype.Text
	Ip        pgtype.Text
	DeviceID  pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.Revoked,
		arg.UserAgent,
		arg.Ip,
		arg.DeviceID,
	)
	return err
}

const findSessionByID = `-- name: FindSessionByID :one
SELECT id, user_id, expires_at, created_at, revoked, user_agent, ip, device_id FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
		&i.UserAgent,
		&i.Ip,
		&i.DeviceID,
	)
	return i, err
}

const findSessionByIDForUpdate = `-- name: FindSessionByIDForUpdate :one
SELECT id, user_id, expires_at, created_at, revoked, user_agent, ip, device_id FROM sessions
WHERE id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) FindSessionByIDForUpdate(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByIDForUpdate, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
		&i.UserAgent,
		&i.Ip,
		&i.DeviceID,
	)
	return i, err
}

const revokeAllSessionsByUserID = `-- name: RevokeAllSessionsByUserID :exec
UPDATE sessions
SET revoked = TRUE
WHERE user_id = $1
`

func (q *Queries) RevokeAllSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsByUserID, userID)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions
SET revoked = TRUE
WHERE id = $1
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, id)
	return err
}
