// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (id, user_id, object_key, status, purpose, file_size, content_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUploadParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ObjectKey   string
	Status      UploadStatus
	Purpose     UploadPurpose
	FileSize    pgtype.Int4
	ContentType pgtype.Text
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.ID,
		arg.UserID,
		arg.ObjectKey,
		arg.Status,
		arg.Purpose,
		arg.FileSize,
		arg.ContentType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getNextProcessingJob = `-- name: GetNextProcessingJob :one
WITH next_job AS (
  SELECT uploads.id
  FROM uploads
  WHERE uploads.status = 'PROCESSING'
    AND uploads.retry_count < $1
    AND (uploads.next_retry_at IS NULL OR uploads.next_retry_at <= now())
    AND (uploads.heartbeat_at IS NULL OR uploads.heartbeat_at < now() - $2::interval)
  ORDER BY uploads.created_at ASC
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
UPDATE uploads u
SET heartbeat_at = now(),
    updated_at   = now()
FROM next_job nj
WHERE u.id = nj.id
RETURNING u.id, u.user_id, u.purpose, u.file_size, u.content_type, u.object_key, u.retry_count
`

type GetNextProcessingJobParams struct {
	RetryCount int32
	Column2    pgtype.Interval
}

type GetNextProcessingJobRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Purpose     UploadPurpose
	FileSize    pgtype.Int4
	ContentType pgtype.Text
	ObjectKey   string
	RetryCount  int32
}

func (q *Queries) GetNextProcessingJob(ctx context.Context, arg GetNextProcessingJobParams) (GetNextProcessingJobRow, error) {
	row := q.db.QueryRow(ctx, getNextProcessingJob, arg.RetryCount, arg.Column2)
	var i GetNextProcessingJobRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.FileSize,
		&i.ContentType,
		&i.ObjectKey,
		&i.RetryCount,
	)
	return i, err
}

const getUploadByID = `-- name: GetUploadByID :one
SELECT id, user_id, object_key, status, purpose, file_size, content_type, failure_reason, created_at, updated_at
FROM uploads
WHERE id = $1
`

type GetUploadByIDRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ObjectKey     string
	Status        UploadStatus
	Purpose       UploadPurpose
	FileSize      pgtype.Int4
	ContentType   pgtype.Text
	FailureReason pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUploadByID(ctx context.Context, id uuid.UUID) (GetUploadByIDRow, error) {
	row := q.db.QueryRow(ctx, getUploadByID, id)
	var i GetUploadByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.Status,
		&i.Purpose,
		&i.FileSize,
		&i.ContentType,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadForUpdate = `-- name: GetUploadForUpdate :one
SELECT id, user_id, status, purpose, object_key
FROM uploads
WHERE id = $1 FOR UPDATE
`

type GetUploadForUpdateRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Status    UploadStatus
	Purpose   UploadPurpose
	ObjectKey string
}

func (q *Queries) GetUploadForUpdate(ctx context.Context, id uuid.UUID) (GetUploadForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUploadForUpdate, id)
	var i GetUploadForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Purpose,
		&i.ObjectKey,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, avatar_upload_id, banner_upload_id
FROM users
WHERE id = $1 FOR UPDATE
`

type GetUserForUpdateRow struct {
	ID             uuid.UUID
	AvatarUploadID pgtype.UUID
	BannerUploadID pgtype.UUID
}

func (q *Queries) GetUserForUpdate(ctx context.Context, id uuid.UUID) (GetUserForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i GetUserForUpdateRow
	err := row.Scan(&i.ID, &i.AvatarUploadID, &i.BannerUploadID)
	return i, err
}

const heartbeatUploadProcessing = `-- name: HeartbeatUploadProcessing :exec
UPDATE uploads
SET heartbeat_at = now(),
    updated_at   = now()
WHERE id = $1
`

func (q *Queries) HeartbeatUploadProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, heartbeatUploadProcessing, id)
	return err
}

const incrementUploadRetry = `-- name: IncrementUploadRetry :exec
UPDATE uploads
SET retry_count   = retry_count + 1,
    next_retry_at = now() + $2::interval,
    heartbeat_at  = NULL,
    updated_at    = now()
WHERE id = $1
`

type IncrementUploadRetryParams struct {
	ID      uuid.UUID
	Column2 pgtype.Interval
}

func (q *Queries) IncrementUploadRetry(ctx context.Context, arg IncrementUploadRetryParams) error {
	_, err := q.db.Exec(ctx, incrementUploadRetry, arg.ID, arg.Column2)
	return err
}

const rejectUpload = `-- name: RejectUpload :exec
UPDATE uploads
SET status = 'REJECTED', failure_reason = $2, updated_at = now()
WHERE id = $1
`

type RejectUploadParams struct {
	ID            uuid.UUID
	FailureReason pgtype.Text
}

func (q *Queries) RejectUpload(ctx context.Context, arg RejectUploadParams) error {
	_, err := q.db.Exec(ctx, rejectUpload, arg.ID, arg.FailureReason)
	return err
}

const updateUploadCompletion = `-- name: UpdateUploadCompletion :exec
UPDATE uploads
SET object_key   = $2,
    content_type = $3,
    status       = $4,
    heartbeat_at = NULL,
    updated_at   = now()
WHERE id = $1
`

type UpdateUploadCompletionParams struct {
	ID          uuid.UUID
	ObjectKey   string
	ContentType pgtype.Text
	Status      UploadStatus
}

func (q *Queries) UpdateUploadCompletion(ctx context.Context, arg UpdateUploadCompletionParams) error {
	_, err := q.db.Exec(ctx, updateUploadCompletion,
		arg.ID,
		arg.ObjectKey,
		arg.ContentType,
		arg.Status,
	)
	return err
}

const updateUploadObjectKeyAndStatus = `-- name: UpdateUploadObjectKeyAndStatus :exec
UPDATE uploads
SET object_key = $2, status = $3, updated_at = now()
WHERE id = $1
`

type UpdateUploadObjectKeyAndStatusParams struct {
	ID        uuid.UUID
	ObjectKey string
	Status    UploadStatus
}

func (q *Queries) UpdateUploadObjectKeyAndStatus(ctx context.Context, arg UpdateUploadObjectKeyAndStatusParams) error {
	_, err := q.db.Exec(ctx, updateUploadObjectKeyAndStatus, arg.ID, arg.ObjectKey, arg.Status)
	return err
}

const updateUploadStatus = `-- name: UpdateUploadStatus :exec
UPDATE uploads
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateUploadStatusParams struct {
	ID     uuid.UUID
	Status UploadStatus
}

func (q *Queries) UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) error {
	_, err := q.db.Exec(ctx, updateUploadStatus, arg.ID, arg.Status)
	return err
}
