// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (id, user_id, object_key, status, purpose, file_size, content_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUploadParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ObjectKey   string
	Status      UploadStatus
	Purpose     UploadPurpose
	FileSize    pgtype.Int4
	ContentType pgtype.Text
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.ID,
		arg.UserID,
		arg.ObjectKey,
		arg.Status,
		arg.Purpose,
		arg.FileSize,
		arg.ContentType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUploadByID = `-- name: GetUploadByID :one
SELECT id, user_id, object_key, status, purpose, file_size, content_type, failure_reason, created_at, updated_at
FROM uploads
WHERE id = $1
`

type GetUploadByIDRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ObjectKey     string
	Status        UploadStatus
	Purpose       UploadPurpose
	FileSize      pgtype.Int4
	ContentType   pgtype.Text
	FailureReason pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUploadByID(ctx context.Context, id uuid.UUID) (GetUploadByIDRow, error) {
	row := q.db.QueryRow(ctx, getUploadByID, id)
	var i GetUploadByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.Status,
		&i.Purpose,
		&i.FileSize,
		&i.ContentType,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadForUpdate = `-- name: GetUploadForUpdate :one
SELECT id, user_id, status, purpose, object_key
FROM uploads
WHERE id = $1 FOR UPDATE
`

type GetUploadForUpdateRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Status    UploadStatus
	Purpose   UploadPurpose
	ObjectKey string
}

func (q *Queries) GetUploadForUpdate(ctx context.Context, id uuid.UUID) (GetUploadForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUploadForUpdate, id)
	var i GetUploadForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Purpose,
		&i.ObjectKey,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, avatar_upload_id, banner_upload_id
FROM users
WHERE id = $1 FOR UPDATE
`

type GetUserForUpdateRow struct {
	ID             uuid.UUID
	AvatarUploadID pgtype.UUID
	BannerUploadID pgtype.UUID
}

func (q *Queries) GetUserForUpdate(ctx context.Context, id uuid.UUID) (GetUserForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i GetUserForUpdateRow
	err := row.Scan(&i.ID, &i.AvatarUploadID, &i.BannerUploadID)
	return i, err
}

const rejectUpload = `-- name: RejectUpload :exec
UPDATE uploads
SET status = 'REJECTED', failure_reason = $2, updated_at = now()
WHERE id = $1
`

type RejectUploadParams struct {
	ID            uuid.UUID
	FailureReason pgtype.Text
}

func (q *Queries) RejectUpload(ctx context.Context, arg RejectUploadParams) error {
	_, err := q.db.Exec(ctx, rejectUpload, arg.ID, arg.FailureReason)
	return err
}

const updateUploadObjectKeyAndStatus = `-- name: UpdateUploadObjectKeyAndStatus :exec
UPDATE uploads
SET object_key = $2, status = $3, updated_at = now()
WHERE id = $1
`

type UpdateUploadObjectKeyAndStatusParams struct {
	ID        uuid.UUID
	ObjectKey string
	Status    UploadStatus
}

func (q *Queries) UpdateUploadObjectKeyAndStatus(ctx context.Context, arg UpdateUploadObjectKeyAndStatusParams) error {
	_, err := q.db.Exec(ctx, updateUploadObjectKeyAndStatus, arg.ID, arg.ObjectKey, arg.Status)
	return err
}

const updateUploadStatus = `-- name: UpdateUploadStatus :exec
UPDATE uploads
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateUploadStatusParams struct {
	ID     uuid.UUID
	Status UploadStatus
}

func (q *Queries) UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) error {
	_, err := q.db.Exec(ctx, updateUploadStatus, arg.ID, arg.Status)
	return err
}
