// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMyUserProfileByID = `-- name: GetMyUserProfileByID :one
SELECT
    u.id, u.username, u.email, u.display_name, u.bio,
    u.avatar_upload_id, u.banner_upload_id,
    u.is_active, u.created_at, u.updated_at,
    up_a.object_key AS avatar_key,
    up_b.object_key AS banner_key
FROM users u
LEFT JOIN uploads up_a ON up_a.id = u.avatar_upload_id AND up_a.status = 'BOUND'
LEFT JOIN uploads up_b ON up_b.id = u.banner_upload_id AND up_b.status = 'BOUND'
WHERE u.id = $1
`

type GetMyUserProfileByIDRow struct {
	ID             uuid.UUID
	Username       string
	Email          string
	DisplayName    pgtype.Text
	Bio            pgtype.Text
	AvatarUploadID pgtype.UUID
	BannerUploadID pgtype.UUID
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AvatarKey      pgtype.Text
	BannerKey      pgtype.Text
}

func (q *Queries) GetMyUserProfileByID(ctx context.Context, id uuid.UUID) (GetMyUserProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getMyUserProfileByID, id)
	var i GetMyUserProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUploadID,
		&i.BannerUploadID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarKey,
		&i.BannerKey,
	)
	return i, err
}

const getPublicUserProfileByUsername = `-- name: GetPublicUserProfileByUsername :one
SELECT
    u.id, u.username, u.email, u.display_name, u.bio,
    u.avatar_upload_id, u.banner_upload_id,
    u.is_active, u.created_at, u.updated_at,
    up_a.object_key AS avatar_key,
    up_b.object_key AS banner_key
FROM users u
LEFT JOIN uploads up_a ON up_a.id = u.avatar_upload_id AND up_a.status = 'BOUND'
LEFT JOIN uploads up_b ON up_b.id = u.banner_upload_id AND up_b.status = 'BOUND'
WHERE u.username = $1 AND u.is_active = true
`

type GetPublicUserProfileByUsernameRow struct {
	ID             uuid.UUID
	Username       string
	Email          string
	DisplayName    pgtype.Text
	Bio            pgtype.Text
	AvatarUploadID pgtype.UUID
	BannerUploadID pgtype.UUID
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AvatarKey      pgtype.Text
	BannerKey      pgtype.Text
}

func (q *Queries) GetPublicUserProfileByUsername(ctx context.Context, username string) (GetPublicUserProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getPublicUserProfileByUsername, username)
	var i GetPublicUserProfileByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUploadID,
		&i.BannerUploadID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarKey,
		&i.BannerKey,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_upload_id = $2, updated_at = now() WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID             uuid.UUID
	AvatarUploadID pgtype.UUID
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.AvatarUploadID)
	return err
}

const updateUserBanner = `-- name: UpdateUserBanner :exec
UPDATE users SET banner_upload_id = $2, updated_at = now() WHERE id = $1
`

type UpdateUserBannerParams struct {
	ID             uuid.UUID
	BannerUploadID pgtype.UUID
}

func (q *Queries) UpdateUserBanner(ctx context.Context, arg UpdateUserBannerParams) error {
	_, err := q.db.Exec(ctx, updateUserBanner, arg.ID, arg.BannerUploadID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    display_name = coalesce($2, display_name),
    bio         = coalesce($3, bio),
    updated_at   = now()
WHERE id = $1
RETURNING id
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID
	DisplayName pgtype.Text
	Bio         pgtype.Text
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.Bio)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
