// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates user credentials and returns an access token, setting a refresh token cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "X-Device-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response-internal_auth_LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Revokes the active session and clears the refresh token cookie.",
                "tags": [
                    "auth"
                ],
                "summary": "User Logout",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Rotates the refresh token cookie and issues a new access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh Access Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "X-Device-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response-internal_auth_LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/RegisterRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "X-Device-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Response-internal_auth_RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-map_string_bool"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                }
            }
        },
        "/uploads/complete": {
            "post": {
                "description": "Marks a pending upload as complete after the file has been uploaded directly to storage.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Complete upload",
                "parameters": [
                    {
                        "description": "Complete upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CompleteUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/uploads/init": {
            "post": {
                "description": "Initiates a new file upload and returns a pre-signed URL for direct upload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Init upload",
                "parameters": [
                    {
                        "description": "Init upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InitUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Response-internal_storage_InitUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/uploads/{id}": {
            "get": {
                "description": "Returns the current status of an upload by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Get upload status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response-internal_storage_UploadStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/users/me": {
            "get": {
                "description": "Returns the full profile of the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get my profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response-internal_user_MyProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "put": {
                "description": "Updates the display name and/or bio of the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update profile",
                "parameters": [
                    {
                        "description": "Update profile request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response-internal_user_MyProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/users/me/avatar": {
            "put": {
                "description": "Sets the avatar of the authenticated user from a completed upload.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update avatar",
                "parameters": [
                    {
                        "description": "Update avatar request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateAvatarRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "delete": {
                "description": "Removes the avatar of the authenticated user.",
                "tags": [
                    "users"
                ],
                "summary": "Delete avatar",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/users/me/banner": {
            "put": {
                "description": "Sets the banner of the authenticated user from a completed upload.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update banner",
                "parameters": [
                    {
                        "description": "Update banner request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateBannerRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "delete": {
                "description": "Removes the banner of the authenticated user.",
                "tags": [
                    "users"
                ],
                "summary": "Delete banner",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/users/{username}": {
            "get": {
                "description": "Returns public profile information for a given username.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get public profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response-internal_user_PublicProfileResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CompleteUploadRequest": {
            "type": "object",
            "required": [
                "upload_id"
            ],
            "properties": {
                "upload_id": {
                    "type": "string"
                }
            }
        },
        "ErrorCode": {
            "type": "string",
            "enum": [
                "PARSE_ERROR",
                "VALIDATION_ERROR",
                "CONFLICT_ERROR",
                "UNAUTHORIZED",
                "FORBIDDEN",
                "NOT_FOUND",
                "UNPROCESSABLE_ENTITY",
                "INTERNAL_SERVER_ERROR"
            ],
            "x-enum-varnames": [
                "ParseCode",
                "ValidationCode",
                "ConflictCode",
                "UnauthorizedCode",
                "ForbiddenCode",
                "NotFoundCode",
                "InvalidCode",
                "InternalServerCode"
            ]
        },
        "ErrorInfo-any": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/ErrorCode"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "ErrorInfo-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/ErrorCode"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/FieldError"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "ErrorInfo-map_string_bool": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/ErrorCode"
                },
                "details": {
                    "$ref": "#/definitions/map_string_bool"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "ErrorResponse-any": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/ErrorInfo-any"
                }
            }
        },
        "ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/ErrorInfo-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                }
            }
        },
        "ErrorResponse-map_string_bool": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/ErrorInfo-map_string_bool"
                }
            }
        },
        "FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "ImageContentType": {
            "type": "string",
            "enum": [
                "image/jpeg",
                "image/png",
                "image/webp"
            ],
            "x-enum-varnames": [
                "ContentTypeJPEG",
                "ContentTypePNG",
                "ContentTypeWebP"
            ]
        },
        "InitUploadRequest": {
            "type": "object",
            "required": [
                "content_type",
                "file_size",
                "purpose"
            ],
            "properties": {
                "content_type": {
                    "$ref": "#/definitions/ImageContentType"
                },
                "file_size": {
                    "type": "integer",
                    "minimum": 1
                },
                "purpose": {
                    "$ref": "#/definitions/UploadPurpose"
                }
            }
        },
        "InitUploadResponse": {
            "type": "object",
            "properties": {
                "upload_id": {
                    "type": "string"
                },
                "upload_url": {
                    "type": "string"
                }
            }
        },
        "LoginRequest": {
            "type": "object",
            "required": [
                "credential",
                "password"
            ],
            "properties": {
                "credential": {
                    "description": "Credential accepts email or username.",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3,
                    "example": "john_doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "StrongP@ssw0rd!"
                }
            }
        },
        "LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTIzNDU2NzgtMTIzNC0xMjM0LTEyMzQtMTIzNDU2Nzg5MDEyIiwiZXhwIjoxNzE5Mjc4NjAwfQ.signature"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 900
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "MyProfileResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "banner_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "PublicProfileResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "banner_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "john.doe@email.com"
                },
                "password": {
                    "description": "Password max length of 72 bytes is due to bcrypt's maximum password length limitation.",
                    "type": "string",
                    "minLength": 8,
                    "example": "StrongP@ssw0rd!"
                },
                "username": {
                    "description": "Username accepts only lowercase alphanumeric characters, dots, and underscores.",
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3,
                    "example": "john_doe"
                }
            }
        },
        "RegisterResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTIzNDU2NzgtMTIzNC0xMjM0LTEyMzQtMTIzNDU2Nzg5MDEyIiwiZXhwIjoxNzE5Mjc4NjAwfQ.signature"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 900
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "Response-internal_auth_LoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/LoginResponse"
                }
            }
        },
        "Response-internal_auth_RegisterResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/RegisterResponse"
                }
            }
        },
        "Response-internal_storage_InitUploadResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/InitUploadResponse"
                }
            }
        },
        "Response-internal_storage_UploadStatusResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/UploadStatusResponse"
                }
            }
        },
        "Response-internal_user_MyProfileResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/MyProfileResponse"
                }
            }
        },
        "Response-internal_user_PublicProfileResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/PublicProfileResponse"
                }
            }
        },
        "UpdateAvatarRequest": {
            "type": "object",
            "required": [
                "upload_id"
            ],
            "properties": {
                "upload_id": {
                    "type": "string"
                }
            }
        },
        "UpdateBannerRequest": {
            "type": "object",
            "required": [
                "upload_id"
            ],
            "properties": {
                "upload_id": {
                    "type": "string"
                }
            }
        },
        "UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string",
                    "maxLength": 500
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 60
                }
            }
        },
        "UploadPurpose": {
            "type": "string",
            "enum": [
                "AVATAR",
                "BANNER",
                "POST_IMAGE"
            ],
            "x-enum-varnames": [
                "PurposeAVATAR",
                "PurposeBANNER",
                "PurposePOSTIMAGE"
            ]
        },
        "UploadStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "REJECTED",
                "EXPIRED",
                "SUPERSEDED",
                "DELETED",
                "BOUND"
            ],
            "x-enum-varnames": [
                "UploadStatusPENDING",
                "UploadStatusPROCESSING",
                "UploadStatusCOMPLETED",
                "UploadStatusREJECTED",
                "UploadStatusEXPIRED",
                "UploadStatusSUPERSEDED",
                "UploadStatusDELETED",
                "UploadStatusBOUND"
            ]
        },
        "UploadStatusResponse": {
            "type": "object",
            "properties": {
                "failure_reason": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/UploadStatus"
                }
            }
        },
        "map_string_bool": {
            "type": "object",
            "additionalProperties": {
                "type": "boolean"
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Artblog API",
	Description:      "Social media API for posts, authentication, and feed management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
