// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates user credentials and returns an access token, setting a refresh token cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.Response-internal_auth_LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-any"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes the active session and clears the refresh token cookie.",
                "tags": [
                    "auth"
                ],
                "summary": "User Logout",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-any"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Rotates the refresh token cookie and issues a new access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh Access Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.Response-internal_auth_LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-any"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.Response-internal_auth_RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-map_string_bool"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_emanuelfelicio_artblogapi_config_response.ErrorCode": {
            "type": "string",
            "enum": [
                "PARSE_ERROR",
                "VALIDATION_ERROR",
                "CONFLICT_ERROR",
                "UNAUTHORIZED",
                "FORBIDDEN",
                "INTERNAL_SERVER_ERROR"
            ],
            "x-enum-varnames": [
                "ParseCode",
                "ValidationCode",
                "ConflictCode",
                "UnauthorizedCode",
                "ForbiddenCode",
                "InternalServerCode"
            ]
        },
        "github_com_emanuelfelicio_artblogapi_config_response.ErrorInfo-any": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorCode"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_emanuelfelicio_artblogapi_config_response.ErrorInfo-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorCode"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_validation.FieldError"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_emanuelfelicio_artblogapi_config_response.ErrorInfo-map_string_bool": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorCode"
                },
                "details": {
                    "$ref": "#/definitions/map_string_bool"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-any": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorInfo-any"
                }
            }
        },
        "github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorInfo-array_github_com_emanuelfelicio_artblogapi_config_validation_FieldError"
                }
            }
        },
        "github_com_emanuelfelicio_artblogapi_config_response.ErrorResponse-map_string_bool": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_emanuelfelicio_artblogapi_config_response.ErrorInfo-map_string_bool"
                }
            }
        },
        "github_com_emanuelfelicio_artblogapi_config_response.Response-internal_auth_LoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_auth.LoginResponse"
                }
            }
        },
        "github_com_emanuelfelicio_artblogapi_config_response.Response-internal_auth_RegisterResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_auth.RegisterResponse"
                }
            }
        },
        "github_com_emanuelfelicio_artblogapi_config_validation.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_auth.LoginRequest": {
            "type": "object",
            "required": [
                "credential",
                "password"
            ],
            "properties": {
                "credential": {
                    "description": "Credential accepts email or username.",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3,
                    "example": "john_doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "StrongP@ssw0rd!"
                }
            }
        },
        "internal_auth.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTIzNDU2NzgtMTIzNC0xMjM0LTEyMzQtMTIzNDU2Nzg5MDEyIiwiZXhwIjoxNzE5Mjc4NjAwfQ.signature"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 900
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "internal_auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "john.doe@email.com"
                },
                "password": {
                    "description": "Password max length of 72 bytes is due to bcrypt's maximum password length limitation.",
                    "type": "string",
                    "minLength": 8,
                    "example": "StrongP@ssw0rd!"
                },
                "username": {
                    "description": "Username accepts only lowercase alphanumeric characters, dots, and underscores.",
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3,
                    "example": "john_doe"
                }
            }
        },
        "internal_auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTIzNDU2NzgtMTIzNC0xMjM0LTEyMzQtMTIzNDU2Nzg5MDEyIiwiZXhwIjoxNzE5Mjc4NjAwfQ.signature"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 900
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "map_string_bool": {
            "type": "object",
            "additionalProperties": {
                "type": "boolean"
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Artblog API",
	Description:      "Social media API for posts, authentication, and feed management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
